package mw.nwra.ewaterpermit.repository;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreApplicationDocument;
import mw.nwra.ewaterpermit.model.CoreLicenseApplication;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreApplicationDocumentRepository extends JpaRepository<CoreApplicationDocument, String> {
	@Query("SELECT d FROM CoreApplicationDocument d WHERE " + " d.coreDocumentCategory.name LIKE %:search% OR "
			+ " d.coreLicenseApplication.id LIKE %:search% OR " + " d.coreDocumentCategory.description LIKE %:search%")
	Page<CoreApplicationDocument> findAll(@Param("search") String search, Pageable pageRequest);

	@Query("SELECT DISTINCT d FROM CoreApplicationDocument d " +
			"LEFT JOIN FETCH d.coreDocumentCategory " +
			"LEFT JOIN FETCH d.coreLicenseApplication app " +
			"LEFT JOIN FETCH app.sysUserAccount user " +
			"LEFT JOIN FETCH app.coreApplicationStatus " +
			"LEFT JOIN FETCH app.coreApplicationStep " +
			"LEFT JOIN FETCH app.coreLicenseType " +
			"WHERE d.coreDocumentCategory.name LIKE %:search% OR " +
			"d.coreLicenseApplication.id LIKE %:search% OR " +
			"d.coreDocumentCategory.description LIKE %:search%")
	Page<CoreApplicationDocument> findAllWithDetails(@Param("search") String search, Pageable pageRequest);

	List<CoreApplicationDocument> findByCoreLicenseApplication(CoreLicenseApplication appl);
}
