package mw.nwra.ewaterpermit.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreLicenseRequirement;
import mw.nwra.ewaterpermit.model.CoreLicenseType;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreLicenseRequirementRepository extends JpaRepository<CoreLicenseRequirement, String> {

	List<CoreLicenseRequirement> findByCoreLicenseType(CoreLicenseType type);

}
