package mw.nwra.ewaterpermit.repository;

import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreLicense;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreLicenseRepository extends JpaRepository<CoreLicense, String> {

	List<CoreLicense> findByLicenseNumber(String number);
	
	List<CoreLicense> findByLicenseNumberOrderByDateCreatedDesc(String number);
	
	List<CoreLicense> findByLicenseNumberAndStatusOrderByDateCreatedDesc(String number, String status);

	// Dashboard queries - optimized to avoid N+1
	Long countByStatus(String status);

	// Optimized query to count licenses expiring within a specific number of days
	@Query(value = "SELECT COUNT(*) FROM core_license " +
			"WHERE status = 'ACTIVE' " +
			"AND expiration_date BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE, INTERVAL :days DAY)",
			nativeQuery = true)
	Long countLicensesExpiringInDays(@Param("days") int days);

	// Expiry-related queries - temporarily disabled for troubleshooting
	// @Query("SELECT l FROM CoreLicense l WHERE l.coreLicenseApplication.sysUserAccount.id = :userId AND l.status = 'ACTIVE' ORDER BY l.expirationDate ASC")
	// List<CoreLicense> findActiveLicensesByUserId(@Param("userId") String userId);

	// @Query("SELECT l FROM CoreLicense l WHERE l.coreLicenseApplication.sysUserAccount.id = :userId AND l.status = 'ACTIVE' AND l.expirationDate BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE, INTERVAL :daysAhead DAY) ORDER BY l.expirationDate ASC")
	// List<CoreLicense> findExpiringLicensesByUserId(@Param("userId") String userId, @Param("daysAhead") int daysAhead);

	// @Query("SELECT l FROM CoreLicense l WHERE l.coreLicenseApplication.sysUserAccount.id = :userId AND l.status = 'ACTIVE' AND l.expirationDate < CURRENT_DATE ORDER BY l.expirationDate DESC")
	// List<CoreLicense> findExpiredLicensesByUserId(@Param("userId") String userId);

	// Query to count active licenses by user/owner ID
	@Query(value = "SELECT COUNT(*) " +
			"FROM core_license l " +
			"JOIN core_license_application app ON l.license_application_id = app.id " +
			"WHERE app.owner_id = :ownerId AND l.status = 'ACTIVE'",
			nativeQuery = true)
	Long countActiveLicensesByUserId(@Param("ownerId") String userId);

	// Optimized queries for my-licenses API with lightweight data fetching
	@Query(value = "SELECT " +
			"l.id, l.license_number, l.date_issued, l.expiration_date, l.status, l.date_updated, l.license_version, l.parent_license_id, " +
			"lt.name as license_type_name, " +
			"ast.name as application_status_name, " +
			"u.first_name, u.last_name, u.email_address, " +
			"asmt.calculated_annual_rental, asmt.rental_quantity, asmt.rental_rate, " +
			"asmt.recommended_schedule_date, asmt.assessment_notes, asmt.license_officer_id, " +
			"asmt.assessment_status, asmt.assessment_files_upload, " +
			"app.location_info, app.application_metadata, app.form_specific_data " +
			"FROM core_license l " +
			"JOIN core_license_application app ON l.license_application_id = app.id " +
			"JOIN core_license_type lt ON app.license_type_id = lt.id " +
			"JOIN core_application_status ast ON app.application_status_id = ast.id " +
			"LEFT JOIN sys_user_account u ON app.owner_id = u.id " +
			"LEFT JOIN core_license_assessment asmt ON app.id = asmt.license_application_id " +
			"ORDER BY l.date_created DESC", nativeQuery = true)
	List<Object[]> findAllLicensesForManager();

	@Query(value = "SELECT " +
			"l.id, l.license_number, l.date_issued, l.expiration_date, l.status, l.date_updated, l.license_version, l.parent_license_id, " +
			"lt.name as license_type_name, " +
			"ast.name as application_status_name " +
			"FROM core_license l " +
			"JOIN core_license_application app ON l.license_application_id = app.id " +
			"JOIN core_license_type lt ON app.license_type_id = lt.id " +
			"JOIN core_application_status ast ON app.application_status_id = ast.id " +
			"WHERE app.owner_id = :ownerId AND l.status = 'ACTIVE' " +
			"ORDER BY l.date_created DESC", nativeQuery = true)
	List<Object[]> findActiveLicensesByOwnerId(@Param("ownerId") String ownerId);

	// License type filtered queries
	@Query(value = "SELECT " +
			"l.id, l.license_number, l.date_issued, l.expiration_date, l.status, l.date_updated, l.license_version, l.parent_license_id, " +
			"lt.name as license_type_name, " +
			"ast.name as application_status_name, " +
			"u.first_name, u.last_name, u.email_address, " +
			"asmt.calculated_annual_rental, asmt.rental_quantity, asmt.rental_rate, " +
			"asmt.recommended_schedule_date, asmt.assessment_notes, asmt.license_officer_id, " +
			"asmt.assessment_status, asmt.assessment_files_upload, " +
			"app.location_info, app.application_metadata, app.form_specific_data " +
			"FROM core_license l " +
			"JOIN core_license_application app ON l.license_application_id = app.id " +
			"JOIN core_license_type lt ON app.license_type_id = lt.id " +
			"JOIN core_application_status ast ON app.application_status_id = ast.id " +
			"LEFT JOIN sys_user_account u ON app.owner_id = u.id " +
			"LEFT JOIN core_license_assessment asmt ON app.id = asmt.license_application_id " +
			"WHERE app.license_type_id = :licenseTypeId " +
			"ORDER BY l.date_created DESC", nativeQuery = true)
	List<Object[]> findAllLicensesForManagerByLicenseType(@Param("licenseTypeId") String licenseTypeId);

	@Query(value = "SELECT " +
			"l.id, l.license_number, l.date_issued, l.expiration_date, l.status, l.date_updated, l.license_version, l.parent_license_id, " +
			"lt.name as license_type_name, " +
			"ast.name as application_status_name " +
			"FROM core_license l " +
			"JOIN core_license_application app ON l.license_application_id = app.id " +
			"JOIN core_license_type lt ON app.license_type_id = lt.id " +
			"JOIN core_application_status ast ON app.application_status_id = ast.id " +
			"WHERE app.owner_id = :ownerId AND l.status = 'ACTIVE' AND app.license_type_id = :licenseTypeId " +
			"ORDER BY l.date_created DESC", nativeQuery = true)
	List<Object[]> findActiveLicensesByOwnerIdAndLicenseType(@Param("ownerId") String ownerId, @Param("licenseTypeId") String licenseTypeId);

	// Optimized query for license data with transfer license support and payment validation
	@Query(value = "SELECT " +
			"l.license_number as permit_number, " +
			"CONCAT(u.first_name, ' ', u.last_name) as applicant_name, " +
			"app.source_owner_fullname, " +
			"l.date_issued, " +
			"l.expiration_date, " +
			"'Director Name' as director_name, " +
			"u.phone_number as contact_phone, " +
			"u.email_address as contact_email, " +
			"CONCAT('License conditions and terms for permit ', l.license_number) as conditions_text, " +
			"CASE " +
				"WHEN l.parent_license_id IS NULL THEN " +
					"CASE WHEN NOT EXISTS (SELECT 1 FROM core_application_payment p JOIN core_fees_type ft ON p.fees_type_id = ft.id WHERE p.license_id = l.id AND ft.name = 'License fees' AND p.payment_status = 'PAID') THEN 1 ELSE 0 END " +
				"ELSE " +
					"CASE WHEN NOT EXISTS (SELECT 1 FROM core_application_payment p JOIN core_fees_type ft ON p.fees_type_id = ft.id WHERE p.license_id = l.parent_license_id AND ft.name = 'License fees' AND p.payment_status = 'PAID') THEN 1 ELSE 0 END " +
			"END as payment_required, " +
			"CASE " +
				"WHEN l.parent_license_id IS NULL THEN " +
					"CASE WHEN EXISTS (SELECT 1 FROM core_application_payment p JOIN core_fees_type ft ON p.fees_type_id = ft.id WHERE p.license_id = l.id AND ft.name = 'License fees' AND p.payment_status = 'AWAITING_VERIFICATION') THEN 1 ELSE 0 END " +
				"ELSE " +
					"CASE WHEN EXISTS (SELECT 1 FROM core_application_payment p JOIN core_fees_type ft ON p.fees_type_id = ft.id WHERE p.license_id = l.parent_license_id AND ft.name = 'License fees' AND p.payment_status = 'AWAITING_VERIFICATION') THEN 1 ELSE 0 END " +
			"END as verification_pending, " +
			"CASE " +
				"WHEN l.parent_license_id IS NULL THEN " +
					"(SELECT p.payment_status FROM core_application_payment p JOIN core_fees_type ft ON p.fees_type_id = ft.id WHERE p.license_id = l.id AND ft.name = 'License fees' LIMIT 1) " +
				"ELSE " +
					"(SELECT p.payment_status FROM core_application_payment p JOIN core_fees_type ft ON p.fees_type_id = ft.id WHERE p.license_id = l.parent_license_id AND ft.name = 'License fees' LIMIT 1) " +
			"END as payment_status, " +
			"CASE " +
				"WHEN l.parent_license_id IS NULL THEN " +
					"(SELECT p.amount_paid FROM core_application_payment p JOIN core_fees_type ft ON p.fees_type_id = ft.id WHERE p.license_id = l.id AND ft.name = 'License fees' LIMIT 1) " +
				"ELSE " +
					"(SELECT p.amount_paid FROM core_application_payment p JOIN core_fees_type ft ON p.fees_type_id = ft.id WHERE p.license_id = l.parent_license_id AND ft.name = 'License fees' LIMIT 1) " +
			"END as amount_paid, " +
			"lt.name as license_type " +
			"FROM core_license l " +
			"JOIN core_license_application app ON l.license_application_id = app.id " +
			"LEFT JOIN sys_user_account u ON app.owner_id = u.id " +
			"LEFT JOIN core_license_type lt ON app.license_type_id = lt.id " +
			"WHERE l.id = :licenseId", nativeQuery = true)
	List<Object[]> findLicenseDataById(@Param("licenseId") String licenseId);

	// Query to get transfer information - find the new license created from a transferred license
	@Query(value = "SELECT " +
			"u.first_name, u.last_name, u.email_address, u.phone_number, " +
			"l.license_number as new_license_number, l.date_created as transfer_date " +
			"FROM core_license l " +
			"JOIN core_license_application app ON l.license_application_id = app.id " +
			"LEFT JOIN sys_user_account u ON app.owner_id = u.id " +
			"WHERE l.parent_license_id = :originalLicenseId", nativeQuery = true)
	List<Object[]> findTransferInfoByOriginalLicenseId(@Param("originalLicenseId") String originalLicenseId);

	// Query to get license type name by ID
	@Query(value = "SELECT name FROM core_license_type WHERE id = :licenseTypeId", nativeQuery = true)
	String findLicenseTypeNameById(@Param("licenseTypeId") String licenseTypeId);

	// Query to find original license type ID for renewal types
	@Query(value = "SELECT id FROM core_license_type " +
			"WHERE name = REPLACE(:renewalTypeName, 'Renewal ', 'New ') " +
			"OR name = REPLACE(:renewalTypeName, 'Renewal of ', 'New ') " +
			"LIMIT 1", nativeQuery = true)
	String findOriginalLicenseTypeIdForRenewal(@Param("renewalTypeName") String renewalTypeName);

	// Query to find all license types that match a base type (New, Renewal, Transfer, and Variation)
	@Query(value = "SELECT id FROM core_license_type " +
			"WHERE name LIKE CONCAT('New ', :baseType) " +
			"OR name LIKE CONCAT('Renewal ', :baseType) " +
			"OR name LIKE CONCAT('Renewal of ', :baseType) " +
			"OR name LIKE CONCAT('Transfer ', :baseType) " +
			"OR name = CONCAT(:baseType, ' variation') " +
			"OR name = :baseType", nativeQuery = true)
	List<String> findLicenseTypesByBaseType(@Param("baseType") String baseType);

	// Query to find active licenses by owner and multiple license types
	@Query(value = "SELECT " +
			"l.id, l.license_number, l.date_issued, l.expiration_date, l.status, l.date_updated, l.license_version, l.parent_license_id, " +
			"lt.name as license_type_name, " +
			"ast.name as application_status_name " +
			"FROM core_license l " +
			"JOIN core_license_application app ON l.license_application_id = app.id " +
			"JOIN core_license_type lt ON app.license_type_id = lt.id " +
			"JOIN core_application_status ast ON app.application_status_id = ast.id " +
			"WHERE app.owner_id = :ownerId AND app.license_type_id IN :licenseTypeIds AND l.status = 'ACTIVE' " +
			"ORDER BY l.date_created DESC", nativeQuery = true)
	List<Object[]> findActiveLicensesByOwnerIdAndLicenseTypes(@Param("ownerId") String ownerId, @Param("licenseTypeIds") List<String> licenseTypeIds);

	// Query to find active licenses that have expired by a given date (for scheduler)
	@Query(value = "SELECT l FROM CoreLicense l " +
			"WHERE l.status = 'ACTIVE' " +
			"AND l.expirationDate <= :expiryDate " +
			"ORDER BY l.expirationDate ASC")
	List<CoreLicense> findActiveLicensesExpiredByDate(@Param("expiryDate") java.sql.Date expiryDate);

	// Queries to find licenses needing notifications at different stages (using native SQL)
	@Query(value = "SELECT * FROM core_license l " +
			"WHERE l.status = 'ACTIVE' " +
			"AND l.expiration_date BETWEEN DATE_ADD(CURRENT_DATE, INTERVAL 89 DAY) AND DATE_ADD(CURRENT_DATE, INTERVAL 91 DAY) " +
			"AND l.notification_3_months_sent IS NULL", nativeQuery = true)
	List<CoreLicense> findLicensesExpiringIn3Months();

	@Query(value = "SELECT * FROM core_license l " +
			"WHERE l.status = 'ACTIVE' " +
			"AND l.expiration_date BETWEEN DATE_ADD(CURRENT_DATE, INTERVAL 50 DAY) AND DATE_ADD(CURRENT_DATE, INTERVAL 65 DAY) " +
			"AND l.notification_2_months_sent IS NULL", nativeQuery = true)
	List<CoreLicense> findLicensesExpiringIn2Months();

	@Query(value = "SELECT * FROM core_license l " +
			"WHERE l.status = 'ACTIVE' " +
			"AND l.expiration_date BETWEEN DATE_ADD(CURRENT_DATE, INTERVAL 29 DAY) AND DATE_ADD(CURRENT_DATE, INTERVAL 31 DAY) " +
			"AND l.notification_1_month_sent IS NULL", nativeQuery = true)
	List<CoreLicense> findLicensesExpiringIn1Month();

	@Query(value = "SELECT * FROM core_license l " +
			"WHERE l.status = 'ACTIVE' " +
			"AND l.expiration_date BETWEEN DATE_ADD(CURRENT_DATE, INTERVAL 6 DAY) AND DATE_ADD(CURRENT_DATE, INTERVAL 8 DAY) " +
			"AND l.notification_1_week_sent IS NULL", nativeQuery = true)
	List<CoreLicense> findLicensesExpiringIn1Week();

	// WRMIS Data Integration Queries (Optimized with JOIN FETCH)
	/**
	 * Find licenses issued between two dates (inclusive) with all related entities
	 * Optimized to avoid N+1 query problem by eagerly loading all relationships
	 */
	@Query("SELECT DISTINCT l FROM CoreLicense l " +
		   "LEFT JOIN FETCH l.coreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource ws " +
		   "LEFT JOIN FETCH ws.coreWaterSourceType " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE l.dateIssued BETWEEN :dateFrom AND :dateTo")
	List<CoreLicense> findByDateIssuedBetween(@Param("dateFrom") java.util.Date dateFrom, @Param("dateTo") java.util.Date dateTo);

	/**
	 * Find licenses issued after a specific date with all related entities
	 */
	@Query("SELECT DISTINCT l FROM CoreLicense l " +
		   "LEFT JOIN FETCH l.coreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource ws " +
		   "LEFT JOIN FETCH ws.coreWaterSourceType " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE l.dateIssued >= :dateFrom")
	List<CoreLicense> findByDateIssuedAfter(@Param("dateFrom") java.util.Date dateFrom);

	/**
	 * Find licenses issued before a specific date with all related entities
	 */
	@Query("SELECT DISTINCT l FROM CoreLicense l " +
		   "LEFT JOIN FETCH l.coreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource ws " +
		   "LEFT JOIN FETCH ws.coreWaterSourceType " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE l.dateIssued <= :dateTo")
	List<CoreLicense> findByDateIssuedBefore(@Param("dateTo") java.util.Date dateTo);

	/**
	 * Find all licenses with all related entities (optimized for WRMIS)
	 * Use this instead of findAll() to avoid N+1 queries
	 */
	@Query("SELECT DISTINCT l FROM CoreLicense l " +
		   "LEFT JOIN FETCH l.coreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource ws " +
		   "LEFT JOIN FETCH ws.coreWaterSourceType " +
		   "LEFT JOIN FETCH app.sysUserAccount")
	List<CoreLicense> findAllWithRelations();

}
