package mw.nwra.ewaterpermit.repository;

import java.util.List;

import mw.nwra.ewaterpermit.model.CoreLicenseApplication;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreApplicationStep;
import mw.nwra.ewaterpermit.model.CoreLicenseType;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreApplicationStepRepository extends JpaRepository<CoreApplicationStep, String> {

	CoreApplicationStep findByName(String name);

	List<CoreApplicationStep> findByCoreLicenseType(CoreLicenseType type);
	
	CoreApplicationStep findFirstByCoreLicenseTypeOrderBySequenceNumberAsc(CoreLicenseType type);
	
	CoreApplicationStep findFirstByCoreLicenseTypeAndSequenceNumberGreaterThanOrderBySequenceNumberAsc(
			CoreLicenseType type, byte currentSequenceNumber);
	
	CoreApplicationStep findFirstByCoreLicenseTypeAndSequenceNumberLessThanOrderBySequenceNumberDesc(
			CoreLicenseType type, byte currentSequenceNumber);

	CoreApplicationStep findFirstByCoreLicenseTypeAndSequenceNumber(CoreLicenseType coreLicenseType, byte sequenceNumber);

	/**
	 * Get next step ID for application using optimized query
	 */
	@Query("""
		SELECT nextStep.id 
		FROM CoreLicenseApplication app 
		JOIN app.coreApplicationStep currentStep 
		JOIN app.coreLicenseType licenseType
		JOIN CoreApplicationStep nextStep ON nextStep.coreLicenseType = licenseType 
		WHERE app.id = :applicationId 
		AND nextStep.sequenceNumber = (currentStep.sequenceNumber + 1)
	""")
	String getNextStepIdForApplication(@Param("applicationId") String applicationId);
}
