package mw.nwra.ewaterpermit.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreLicense;
import mw.nwra.ewaterpermit.model.CoreLicenseApplication;
import mw.nwra.ewaterpermit.model.SysUserAccount;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreLicenseApplicationRepository extends JpaRepository<CoreLicenseApplication, String> {

	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationPayments payments " +
		   "LEFT JOIN FETCH payments.coreFeesType " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreApplicationStep step " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource " +
		   "LEFT JOIN FETCH app.sysUserAccount userAccount " +
		   "LEFT JOIN FETCH userAccount.coreDistrict " +
		   "LEFT JOIN FETCH userAccount.sysAccountStatus " +
		   "LEFT JOIN FETCH userAccount.sysSalutation " +
		   "LEFT JOIN FETCH userAccount.sysUserGroup")
	List<CoreLicenseApplication> findAllWithPayments();


	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationPayments payments " +
		   "LEFT JOIN FETCH payments.coreFeesType " +
		   "LEFT JOIN FETCH app.sourceWru sourceWru " +
		   "LEFT JOIN FETCH sourceWru.coreWaterResourceArea " +
		   "LEFT JOIN FETCH app.destWru destWru " +
		   "LEFT JOIN FETCH destWru.coreWaterResourceArea " +
		   "LEFT JOIN FETCH app.sourceLandRegime " +
		   "LEFT JOIN FETCH app.destLandRegime " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreApplicationStep " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE app.id = :id")
	Optional<CoreLicenseApplication> findByIdWithPayments(@Param("id") String id);

	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationPayments payments " +
		   "LEFT JOIN FETCH payments.coreFeesType " +
		   "LEFT JOIN FETCH app.sourceWru sourceWru " +
		   "LEFT JOIN FETCH sourceWru.coreWaterResourceArea " +
		   "LEFT JOIN FETCH app.destWru destWru " +
		   "LEFT JOIN FETCH destWru.coreWaterResourceArea " +
		   "LEFT JOIN FETCH app.sourceLandRegime " +
		   "LEFT JOIN FETCH app.destLandRegime " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreApplicationStep " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE app.currentLicense = :licence")
	CoreLicenseApplication findByCurrentLicenseWithPayments(@Param("licence") CoreLicense licence);

	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationPayments payments " +
		   "LEFT JOIN FETCH payments.coreFeesType " +
		   "LEFT JOIN FETCH app.sourceWru sourceWru " +
		   "LEFT JOIN FETCH sourceWru.coreWaterResourceArea " +
		   "LEFT JOIN FETCH app.destWru destWru " +
		   "LEFT JOIN FETCH destWru.coreWaterResourceArea " +
		   "LEFT JOIN FETCH app.sourceLandRegime " +
		   "LEFT JOIN FETCH app.destLandRegime " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreApplicationStep " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE app.sysUserAccount = :applicant")
	List<CoreLicenseApplication> findBySysUserAccountWithPayments(@Param("applicant") SysUserAccount applicant);

	CoreLicenseApplication findByCurrentLicense(CoreLicense licence);

	List<CoreLicenseApplication> findBySysUserAccount(SysUserAccount applicant);

	// Dashboard queries
	@Query("SELECT COUNT(app) FROM CoreLicenseApplication app WHERE app.coreApplicationStatus.name = :statusName")
	Long countByApplicationStatusName(@Param("statusName") String statusName);

	@Query("SELECT status.name, COUNT(app) FROM CoreLicenseApplication app JOIN app.coreApplicationStatus status GROUP BY status.name")
	List<Object[]> getApplicationsByStatus();

	@Query("SELECT type.name, COUNT(app) FROM CoreLicenseApplication app JOIN app.coreLicenseType type GROUP BY type.name")
	List<Object[]> getApplicationsByLicenseType();

	@Query("SELECT MONTH(app.dateSubmitted), COUNT(app) FROM CoreLicenseApplication app WHERE YEAR(app.dateSubmitted) = YEAR(CURRENT_DATE) GROUP BY MONTH(app.dateSubmitted)")
	List<Object[]> getMonthlyApplicationsCurrentYear();
	
	// Role-specific dashboard queries
	@Query("SELECT COUNT(app) FROM CoreLicenseApplication app WHERE app.sysUserAccount.id = :userId")
	Long countByUserId(@Param("userId") String userId);
	
	@Query("SELECT COUNT(app) FROM CoreLicenseApplication app WHERE app.sysUserAccount.id = :userId AND app.coreApplicationStatus.name = :status")
	Long countByUserIdAndStatus(@Param("userId") String userId, @Param("status") String status);

	@Query("SELECT COUNT(app) FROM CoreLicenseApplication app WHERE app.sysUserAccount.id = :userId AND app.coreApplicationStatus.name NOT IN ('REJECT', 'REJECTED', 'APPROVED')")
	Long countPendingApplicationsByUserId(@Param("userId") String userId);
	
	@Query("SELECT app.id, app.dateCreated, app.coreApplicationStatus.name, app.coreLicenseType.name FROM CoreLicenseApplication app " +
		   "WHERE app.sysUserAccount.id = :userId " +
		   "ORDER BY app.dateCreated DESC")
	List<Object[]> getRecentApplicationsByUserId(@Param("userId") String userId, Pageable pageable);
	
	@Query("SELECT app.id, app.dateCreated, app.sysUserAccount.firstName, app.sysUserAccount.lastName FROM CoreLicenseApplication app " +
		   "WHERE app.coreApplicationStatus.name = :status " +
		   "ORDER BY app.dateCreated DESC")
	List<Object[]> getRecentApplicationsByStatus(@Param("status") String status, Pageable pageable);
	
	@Query("SELECT COUNT(app) FROM CoreLicenseApplication app WHERE MONTH(app.dateCreated) = MONTH(CURRENT_DATE) AND YEAR(app.dateCreated) = YEAR(CURRENT_DATE)")
	Long countApplicationsThisMonth();
	
	@Query("SELECT COUNT(app) FROM CoreLicenseApplication app WHERE app.coreApplicationStatus.name = :status AND MONTH(app.dateCreated) = MONTH(CURRENT_DATE) AND YEAR(app.dateCreated) = YEAR(CURRENT_DATE)")
	Long countByStatusAndCurrentMonth(@Param("status") String status);
	
	@Query("SELECT 'Officer Performance', COUNT(app) FROM CoreLicenseApplication app GROUP BY app.coreApplicationStatus.name")
	List<Object[]> getOfficerPerformanceMetrics();
	
	@Query("SELECT COALESCE(ws.name, 'Unknown'), COUNT(app) FROM CoreLicenseApplication app LEFT JOIN app.coreWaterSource ws GROUP BY ws.name")
	List<Object[]> getApplicationsByWaterSource();
	
	@Query("SELECT COALESCE(wru.id, 'Unknown'), COUNT(app) FROM CoreLicenseApplication app LEFT JOIN app.destWru wru GROUP BY wru.id")
	List<Object[]> getApplicationsByRegion();
	
	@Query("SELECT YEAR(app.dateCreated), COUNT(app) FROM CoreLicenseApplication app GROUP BY YEAR(app.dateCreated) ORDER BY YEAR(app.dateCreated)")
	List<Object[]> getYearlyApplicationTrends();
	
	@Query("SELECT app.id, app.sysUserAccount.firstName, app.sysUserAccount.lastName, app.coreLicenseType.name, " +
		   "app.licenseFee, app.applicationPriority, app.coreApplicationStatus.name, " +
		   "CASE " +
		   "  WHEN app.applicationPriority = 'EMERGENCY' THEN 'Emergency Priority Application' " +
		   "  WHEN app.licenseFee >= 100000 THEN 'High License Fee (>= MWK 100,000)' " +
		   "  WHEN app.licenseFee >= 50000 THEN 'Significant License Fee (>= MWK 50,000)' " +
		   "  WHEN app.coreApplicationStatus.name IN ('CEO_REVIEW', 'DRS_REVIEW', 'MANAGER_REVIEW') THEN 'Pending Executive Review' " +
		   "  ELSE 'High Value Application' " +
		   "END as highValueReason " +
		   "FROM CoreLicenseApplication app " +
		   "WHERE (app.applicationPriority = 'EMERGENCY' " +
		   "   OR app.licenseFee >= 50000 " +
		   "   OR app.coreApplicationStatus.name IN ('CEO_REVIEW', 'DRS_REVIEW', 'MANAGER_REVIEW')) " +
		   "   AND app.coreApplicationStatus.name NOT IN ('APPROVED', 'REJECTED', 'CANCELLED') " +
		   "ORDER BY " +
		   "  CASE WHEN app.applicationPriority = 'EMERGENCY' THEN 1 ELSE 2 END, " +
		   "  app.licenseFee DESC, " +
		   "  app.dateCreated DESC")
	List<Object[]> getHighValueApplications(Pageable pageable);

	@Query("SELECT status.name, COUNT(app) FROM CoreLicenseApplication app JOIN app.coreApplicationStatus status WHERE app.sysUserAccount.id = :userId GROUP BY status.name")
	List<Object[]> getApplicationStatusDistributionByUserId(@Param("userId") String userId);

	@Query("SELECT DISTINCT app.id, app.applicationType, app.dateSubmitted, app.dateCreated, " +
		   "status.name, type.name, type.id, " +
		   "appFeePayment.paymentStatus, appFeePayment.amountPaid, " +
		   "licenseFeePayment.paymentStatus, licenseFeePayment.amountPaid, " +
		   "app.applicationMetadata, type.applicationFees, type.licenseFees, " +
		   "app.applicationPriority, app.emergencyReason, app.emergencyJustificationFile, app.emergencySubmittedDate, " +
		   "app.licenseFee, app.licenseFeeSetByUserId, app.licenseFeeSetDate " +
		   "FROM CoreLicenseApplication app " +
		   "LEFT JOIN app.coreApplicationStatus status " +
		   "LEFT JOIN app.coreLicenseType type " +
		   "LEFT JOIN app.sysUserAccount userAccount " +
		   "LEFT JOIN app.coreApplicationPayments appFeePayment ON appFeePayment.coreFeesType.name = 'Application fee' " +
		   "LEFT JOIN app.coreApplicationPayments licenseFeePayment ON licenseFeePayment.coreFeesType.name = 'License fees' " +
		   "WHERE userAccount.username = :username " +
		   "ORDER BY app.dateCreated DESC")
	List<Object[]> findAllByUsernameWithAllAssociations(@Param("username") String username);

	@Query(value = "SELECT application_metadata, form_specific_data, license_fee, license_fee_set_by_user_id, license_fee_set_date FROM core_license_application WHERE id = :id", nativeQuery = true)
	Object findApplicationDetailsById(@Param("id") String id);

	@Query(value = "SELECT app.id FROM core_license_application app " +
			"JOIN core_license license ON license.license_application_id = app.id " +
			"WHERE license.id = :licenseId", nativeQuery = true)
	List<Object[]> findApplicationByLicenseId(@Param("licenseId") String licenseId);

	@Query(value = "SELECT app.id, app.application_type, app.date_submitted, app.date_created, " +
		   "status.name, type.name, type.id, payments.payment_status, fees.name, app.application_metadata, app.client_info, app.location_info, " +
		   "step.id, step.name, step.sequence_number " +
		   "FROM core_license_application app " +
		   "LEFT JOIN core_application_status status ON app.application_status_id = status.id " +
		   "LEFT JOIN core_license_type type ON app.license_type_id = type.id " +
		   "LEFT JOIN core_application_payment payments ON app.id = payments.license_application_id " +
		   "LEFT JOIN core_fees_type fees ON payments.fees_type_id = fees.id " +
		   "LEFT JOIN core_application_step step ON app.application_step_id = step.id", 
		   countQuery = "SELECT COUNT(*) FROM core_license_application app", nativeQuery = true)
	List<Object[]> findAllWithPayments(Pageable pageable);

	@Query(value = "SELECT DISTINCT app.id, app.application_type, app.date_submitted, app.date_created, " +
		   "status.name, type.name, type.id, payments.payment_status, fees.name, app.application_metadata, app.client_info, app.location_info, " +
		   "step.id, step.name, step.sequence_number, " +
		   "user_account.id, user_account.first_name, user_account.last_name, user_account.username, user_account.email_address, " +
		   "payments.amount_paid, payments.id, payments.payment_method, payments.date_created, " +
		   "app.application_priority, app.emergency_reason, app.emergency_justification_file, app.emergency_submitted_date, " +
		   "app.license_fee, " +
		   "assessment.calculated_annual_rental, assessment.rental_quantity, assessment.rental_rate, " +
		   "assessment.recommended_schedule_date, assessment.assessment_notes, assessment.license_officer_id, " +
		   "assessment.assessment_status, assessment.assessment_files_upload " +
		   "FROM core_license_application app " +
		   "LEFT JOIN core_application_status status ON app.application_status_id = status.id " +
		   "LEFT JOIN core_license_type type ON app.license_type_id = type.id " +
		   "LEFT JOIN core_application_payment payments ON payments.id = (" +
		   "    SELECT p.id FROM core_application_payment p WHERE p.license_application_id = app.id ORDER BY p.date_created DESC LIMIT 1" +
		   ") " +
		   "LEFT JOIN core_fees_type fees ON payments.fees_type_id = fees.id " +
		   "LEFT JOIN core_application_step step ON app.application_step_id = step.id " +
		   "LEFT JOIN sys_user_account user_account ON app.user_account_id = user_account.id " +
		   "LEFT JOIN core_license_assessment assessment ON assessment.license_application_id = app.id " +
		   "WHERE (:userRole = 'admin') OR " +
		   "(:userRole IN ('accountant') AND ((step.sequence_number = 0 OR step.sequence_number = 5 OR step.sequence_number = 6) AND (EXISTS (SELECT 1 FROM core_application_payment p WHERE p.license_application_id = app.id AND UPPER(p.payment_status) IN ('AWAITING_APPROVAL', 'REJECTED')) OR EXISTS (SELECT 1 FROM core_application_document d WHERE d.license_application_id = app.id AND UPPER(d.status) IN ('AWAITING_APPROVAL', 'REJECTED'))))) OR " +
		   "(:userRole IN ('licensing officer', 'licensing_officer', 'license officer', 'license_officer') AND step.sequence_number = 1) OR " +
		   "(:userRole IN ('senior licensing officer', 'senior_licensing_officer', 'senior license officer', 'senior_license_officer') AND step.sequence_number = 2) OR " +
		   "(:userRole IN ('licensing manager', 'licensing_manager', 'license manager', 'license_manager') AND step.sequence_number = 3) OR " +
		   "(:userRole = 'drs' AND step.sequence_number = 4) OR " +
		   "(:userRole = 'ceo' AND step.sequence_number = 5) " +
		   "ORDER BY app.date_created DESC",
		   countQuery = "SELECT COUNT(*) FROM core_license_application app " +
		   "LEFT JOIN core_application_step step ON app.application_step_id = step.id " +
		   "WHERE (:userRole = 'admin') OR " +
		   "(:userRole IN ('accountant') AND ((step.sequence_number = 0 OR step.sequence_number = 5 OR step.sequence_number = 6) AND (EXISTS (SELECT 1 FROM core_application_payment p WHERE p.license_application_id = app.id AND UPPER(p.payment_status) IN ('AWAITING_APPROVAL', 'REJECTED')) OR EXISTS (SELECT 1 FROM core_application_document d WHERE d.license_application_id = app.id AND UPPER(d.status) IN ('AWAITING_APPROVAL', 'REJECTED'))))) OR " +
		   "(:userRole IN ('licensing officer', 'licensing_officer', 'license officer', 'license_officer') AND step.sequence_number = 1) OR " +
		   "(:userRole IN ('senior licensing officer', 'senior_licensing_officer', 'senior license officer', 'senior_license_officer') AND step.sequence_number = 2) OR " +
		   "(:userRole IN ('licensing manager', 'licensing_manager', 'license manager', 'license_manager') AND step.sequence_number = 3) OR " +
		   "(:userRole = 'drs' AND step.sequence_number = 4) OR " +
		   "(:userRole = 'ceo' AND step.sequence_number = 5)", nativeQuery = true)
	List<Object[]> findAllWithPaymentsByRole(@Param("userRole") String userRole, Pageable pageable);

	@Query(value = "SELECT DISTINCT app.id, app.application_type, app.date_submitted, app.date_created, " +
		   "status.name, type.name, type.id, payments.payment_status, fees.name, app.application_metadata, app.client_info, app.location_info, " +
		   "step.id, step.name, step.sequence_number, " +
		   "user_account.id, user_account.first_name, user_account.last_name, user_account.username, user_account.email_address, " +
		   "payments.amount_paid, payments.id, payments.payment_method, payments.date_created, " +
		   "app.application_priority, app.emergency_reason, app.emergency_justification_file, app.emergency_submitted_date, " +
		   "app.license_fee, " +
		   "assessment.calculated_annual_rental, assessment.rental_quantity, assessment.rental_rate, " +
		   "assessment.recommended_schedule_date, assessment.assessment_notes, assessment.license_officer_id, " +
		   "assessment.assessment_status, assessment.assessment_files_upload " +
		   "FROM core_license_application app " +
		   "LEFT JOIN core_application_status status ON app.application_status_id = status.id " +
		   "LEFT JOIN core_license_type type ON app.license_type_id = type.id " +
		   "LEFT JOIN core_application_payment payments ON payments.id = (" +
		   "    SELECT p.id FROM core_application_payment p WHERE p.license_application_id = app.id ORDER BY p.date_created DESC LIMIT 1" +
		   ") " +
		   "LEFT JOIN core_fees_type fees ON payments.fees_type_id = fees.id " +
		   "LEFT JOIN core_application_step step ON app.application_step_id = step.id " +
		   "LEFT JOIN sys_user_account user_account ON app.user_account_id = user_account.id " +
		   "LEFT JOIN core_license_assessment assessment ON assessment.license_application_id = app.id " +
		   "WHERE ((:userRole = 'admin') OR " +
		   "(:userRole IN ('accountant') AND ((step.sequence_number = 0 OR step.sequence_number = 5 OR step.sequence_number = 6) AND (EXISTS (SELECT 1 FROM core_application_payment p WHERE p.license_application_id = app.id AND UPPER(p.payment_status) IN ('AWAITING_APPROVAL', 'REJECTED')) OR EXISTS (SELECT 1 FROM core_application_document d WHERE d.license_application_id = app.id AND UPPER(d.status) IN ('AWAITING_APPROVAL', 'REJECTED'))))) OR " +
		   "(:userRole IN ('licensing officer', 'licensing_officer', 'license officer', 'license_officer') AND step.sequence_number = 1) OR " +
		   "(:userRole IN ('senior licensing officer', 'senior_licensing_officer', 'senior license officer', 'senior_license_officer') AND step.sequence_number = 2) OR " +
		   "(:userRole IN ('licensing manager', 'licensing_manager', 'license manager', 'license_manager') AND step.sequence_number = 3) OR " +
		   "(:userRole = 'drs' AND step.sequence_number = 4) OR " +
		   "(:userRole = 'ceo' AND step.sequence_number = 5)) " +
		   "AND (:dateFrom IS NULL OR app.date_created >= STR_TO_DATE(:dateFrom, '%Y-%m-%d')) " +
		   "AND (:dateTo IS NULL OR app.date_created <= STR_TO_DATE(CONCAT(:dateTo, ' 23:59:59'), '%Y-%m-%d %H:%i:%s')) " +
		   "ORDER BY app.date_created DESC", nativeQuery = true)
	List<Object[]> findAllWithPaymentsByRoleAndDateRange(@Param("userRole") String userRole, @Param("dateFrom") String dateFrom, @Param("dateTo") String dateTo, Pageable pageable);

	/**
	 * Find application by ID without loading any relationships (returns only the application entity)
	 */
	@Query("SELECT app FROM CoreLicenseApplication app WHERE app.id = :id")
	Optional<CoreLicenseApplication> findByIdSimple(@Param("id") String id);

	/**
	 * OPTIMIZED: Fetch applications with all basic relationships
	 * Step 1: Load app + status, type, step, water source
	 */
	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreApplicationStep " +
		   "LEFT JOIN FETCH app.coreWaterSource " +
		   "WHERE app.id IN :ids")
	List<CoreLicenseApplication> findByIdInWithEagerLoading(@Param("ids") List<String> ids);

	/**
	 * Step 2: Load user accounts with nested relationships
	 */
	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "JOIN FETCH app.sysUserAccount user " +
		   "LEFT JOIN FETCH user.sysUserGroup " +
		   "LEFT JOIN FETCH user.coreDistrict " +
		   "LEFT JOIN FETCH user.sysSalutation " +
		   "WHERE app.id IN :ids")
	List<CoreLicenseApplication> fetchUserAccounts(@Param("ids") List<String> ids);

	/**
	 * Step 3: Load water resource units with areas
	 */
	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.destWru destWru " +
		   "LEFT JOIN FETCH destWru.coreWaterResourceArea " +
		   "LEFT JOIN FETCH app.sourceWru sourceWru " +
		   "LEFT JOIN FETCH sourceWru.coreWaterResourceArea " +
		   "WHERE app.id IN :ids")
	List<CoreLicenseApplication> fetchWaterResourceUnits(@Param("ids") List<String> ids);

	/**
	 * EFFICIENT: Check if a PENDING transfer exists for a license
	 * Returns true only if a transfer is actively in progress (not completed/rejected/cancelled)
	 * APPROVED transfers are complete and should NOT block new transfers
	 */
	@Query("SELECT CASE WHEN COUNT(app) > 0 THEN true ELSE false END " +
		   "FROM CoreLicenseApplication app " +
		   "JOIN app.coreApplicationStatus status " +
		   "WHERE app.applicationType = 'TRANSFER' " +
		   "AND app.originalLicenseId = :originalLicenseId " +
		   "AND status.name NOT IN ('REJECTED', 'CANCELLED', 'APPROVED')")
	boolean existsPendingOrApprovedTransferForLicense(@Param("originalLicenseId") String originalLicenseId);

	// WRMIS Data Integration Queries (Optimized with JOIN FETCH)
	/**
	 * Find applications submitted between two dates (inclusive) with all related entities
	 * Optimized to avoid N+1 query problem by eagerly loading all relationships
	 */
	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreApplicationStep step " +
		   "LEFT JOIN FETCH step.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource ws " +
		   "LEFT JOIN FETCH ws.coreWaterSourceType " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE app.dateSubmitted BETWEEN :dateFrom AND :dateTo")
	List<CoreLicenseApplication> findByDateSubmittedBetween(@Param("dateFrom") java.util.Date dateFrom, @Param("dateTo") java.util.Date dateTo);

	/**
	 * Find applications submitted after a specific date with all related entities
	 */
	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreApplicationStep step " +
		   "LEFT JOIN FETCH step.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource ws " +
		   "LEFT JOIN FETCH ws.coreWaterSourceType " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE app.dateSubmitted >= :dateFrom")
	List<CoreLicenseApplication> findByDateSubmittedAfter(@Param("dateFrom") java.util.Date dateFrom);

	/**
	 * Find applications submitted before a specific date with all related entities
	 */
	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreApplicationStep step " +
		   "LEFT JOIN FETCH step.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource ws " +
		   "LEFT JOIN FETCH ws.coreWaterSourceType " +
		   "LEFT JOIN FETCH app.sysUserAccount " +
		   "WHERE app.dateSubmitted <= :dateTo")
	List<CoreLicenseApplication> findByDateSubmittedBefore(@Param("dateTo") java.util.Date dateTo);

	/**
	 * Find all applications with all related entities (optimized for WRMIS)
	 * Use this instead of findAll() to avoid N+1 queries
	 */
	@Query("SELECT DISTINCT app FROM CoreLicenseApplication app " +
		   "LEFT JOIN FETCH app.coreApplicationStatus " +
		   "LEFT JOIN FETCH app.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreApplicationStep step " +
		   "LEFT JOIN FETCH step.coreLicenseType " +
		   "LEFT JOIN FETCH app.coreWaterSource ws " +
		   "LEFT JOIN FETCH ws.coreWaterSourceType " +
		   "LEFT JOIN FETCH app.sysUserAccount")
	List<CoreLicenseApplication> findAllWithRelations();

}
