package mw.nwra.ewaterpermit.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreLicenseApplication;
import mw.nwra.ewaterpermit.model.CoreLicenseApplicationActivity;

import java.util.List;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreLicenseApplicationActivityRepository
		extends JpaRepository<CoreLicenseApplicationActivity, String> {

	CoreLicenseApplicationActivity findByCoreLicenseApplication(CoreLicenseApplication application);

	// Find distinct application IDs handled by users with a specific role
	@Query(value = "SELECT DISTINCT la.* FROM core_license_application la " +
			"INNER JOIN core_license_application_activity act ON act.license_application_id = la.id " +
			"INNER JOIN sys_user_account u ON u.id = act.user_account_id " +
			"INNER JOIN sys_user_group g ON g.id = u.user_group_id " +
			"WHERE LOWER(g.name) = LOWER(:roleName) " +
			"ORDER BY la.date_created DESC",
			nativeQuery = true)
	List<CoreLicenseApplication> findApplicationsByUserRole(@Param("roleName") String roleName);

	// Find distinct application IDs handled by a specific user
	@Query(value = "SELECT DISTINCT la.* FROM core_license_application la " +
			"INNER JOIN core_license_application_activity act ON act.license_application_id = la.id " +
			"WHERE act.user_account_id = :userId " +
			"ORDER BY la.date_created DESC",
			nativeQuery = true)
	List<CoreLicenseApplication> findApplicationsByUserId(@Param("userId") String userId);

	/**
	 * OPTIMIZED: Single native SQL query that returns all data as Object[] - same approach as the fast endpoint
	 * This avoids all N+1 queries and ORM overhead by using raw SQL
	 * Uses window function (ROW_NUMBER) instead of correlated subquery for better performance
	 */
	@Query(value = "SELECT app.id, app.application_type, app.date_submitted, app.date_created, " +
			"status.name, type.name, type.id, latest_payment.payment_status, fees.name, " +
			"app.application_metadata, app.client_info, app.location_info, app.form_specific_data, " +
			"step.id, step.name, step.sequence_number, " +
			"user_account.id, user_account.first_name, user_account.last_name, user_account.username, user_account.email_address, " +
			"latest_payment.amount_paid, latest_payment.id, latest_payment.payment_method, latest_payment.date_created, " +
			"app.application_priority, app.emergency_reason, app.emergency_justification_file, app.emergency_submitted_date, " +
			"app.license_fee " +
			"FROM core_license_application app " +
			"INNER JOIN core_license_application_activity act ON act.license_application_id = app.id " +
			"INNER JOIN sys_user_account u ON u.id = act.user_account_id " +
			"INNER JOIN sys_user_group g ON g.id = u.user_group_id " +
			"LEFT JOIN core_application_status status ON app.application_status_id = status.id " +
			"LEFT JOIN core_license_type type ON app.license_type_id = type.id " +
			"LEFT JOIN ( " +
			"    SELECT p.id, p.license_application_id, p.payment_status, p.amount_paid, " +
			"           p.payment_method, p.date_created, p.fees_type_id, " +
			"           ROW_NUMBER() OVER (PARTITION BY p.license_application_id ORDER BY p.date_created DESC) as rn " +
			"    FROM core_application_payment p " +
			") latest_payment ON latest_payment.license_application_id = app.id AND latest_payment.rn = 1 " +
			"LEFT JOIN core_fees_type fees ON latest_payment.fees_type_id = fees.id " +
			"LEFT JOIN core_application_step step ON app.application_step_id = step.id " +
			"LEFT JOIN sys_user_account user_account ON app.user_account_id = user_account.id " +
			"WHERE LOWER(g.name) = LOWER(:roleName) " +
			"GROUP BY app.id, app.application_type, app.date_submitted, app.date_created, " +
			"         status.name, type.name, type.id, latest_payment.payment_status, fees.name, " +
			"         app.application_metadata, app.client_info, app.location_info, app.form_specific_data, " +
			"         step.id, step.name, step.sequence_number, " +
			"         user_account.id, user_account.first_name, user_account.last_name, user_account.username, user_account.email_address, " +
			"         latest_payment.amount_paid, latest_payment.id, latest_payment.payment_method, latest_payment.date_created, " +
			"         app.application_priority, app.emergency_reason, app.emergency_justification_file, app.emergency_submitted_date, " +
			"         app.license_fee " +
			"ORDER BY app.date_created DESC",
			countQuery = "SELECT COUNT(DISTINCT app.id) FROM core_license_application app " +
					"INNER JOIN core_license_application_activity act ON act.license_application_id = app.id " +
					"INNER JOIN sys_user_account u ON u.id = act.user_account_id " +
					"INNER JOIN sys_user_group g ON g.id = u.user_group_id " +
					"WHERE LOWER(g.name) = LOWER(:roleName)",
			nativeQuery = true)
	org.springframework.data.domain.Page<Object[]> findApplicationHistoryByRole(@Param("roleName") String roleName, Pageable pageable);

	/**
	 * OPTIMIZED: Returns ALL applications without role filtering (for DRS and admin users)
	 * Uses window function (ROW_NUMBER) instead of correlated subquery for better performance
	 */
	@Query(value = "SELECT app.id, app.application_type, app.date_submitted, app.date_created, " +
			"status.name, type.name, type.id, latest_payment.payment_status, fees.name, " +
			"app.application_metadata, app.client_info, app.location_info, app.form_specific_data, " +
			"step.id, step.name, step.sequence_number, " +
			"user_account.id, user_account.first_name, user_account.last_name, user_account.username, user_account.email_address, " +
			"latest_payment.amount_paid, latest_payment.id, latest_payment.payment_method, latest_payment.date_created, " +
			"app.application_priority, app.emergency_reason, app.emergency_justification_file, app.emergency_submitted_date, " +
			"app.license_fee " +
			"FROM core_license_application app " +
			"LEFT JOIN core_application_status status ON app.application_status_id = status.id " +
			"LEFT JOIN core_license_type type ON app.license_type_id = type.id " +
			"LEFT JOIN ( " +
			"    SELECT p.id, p.license_application_id, p.payment_status, p.amount_paid, " +
			"           p.payment_method, p.date_created, p.fees_type_id, " +
			"           ROW_NUMBER() OVER (PARTITION BY p.license_application_id ORDER BY p.date_created DESC) as rn " +
			"    FROM core_application_payment p " +
			") latest_payment ON latest_payment.license_application_id = app.id AND latest_payment.rn = 1 " +
			"LEFT JOIN core_fees_type fees ON latest_payment.fees_type_id = fees.id " +
			"LEFT JOIN core_application_step step ON app.application_step_id = step.id " +
			"LEFT JOIN sys_user_account user_account ON app.user_account_id = user_account.id " +
			"ORDER BY app.date_created DESC",
			countQuery = "SELECT COUNT(app.id) FROM core_license_application app",
			nativeQuery = true)
	org.springframework.data.domain.Page<Object[]> findAllApplicationHistory(Pageable pageable);

	/**
	 * OPTIMIZED: Returns applications filtered by role AND date range
	 * Uses window function (ROW_NUMBER) instead of correlated subquery for better performance
	 * Note: This method should only be called when both dateFrom and dateTo are non-null
	 */
	@Query(value = "SELECT app.id, app.application_type, app.date_submitted, app.date_created, " +
			"status.name, type.name, type.id, latest_payment.payment_status, fees.name, " +
			"app.application_metadata, app.client_info, app.location_info, app.form_specific_data, " +
			"step.id, step.name, step.sequence_number, " +
			"user_account.id, user_account.first_name, user_account.last_name, user_account.username, user_account.email_address, " +
			"latest_payment.amount_paid, latest_payment.id, latest_payment.payment_method, latest_payment.date_created, " +
			"app.application_priority, app.emergency_reason, app.emergency_justification_file, app.emergency_submitted_date, " +
			"app.license_fee " +
			"FROM core_license_application app " +
			"INNER JOIN core_license_application_activity act ON act.license_application_id = app.id " +
			"INNER JOIN sys_user_account u ON u.id = act.user_account_id " +
			"INNER JOIN sys_user_group g ON g.id = u.user_group_id " +
			"LEFT JOIN core_application_status status ON app.application_status_id = status.id " +
			"LEFT JOIN core_license_type type ON app.license_type_id = type.id " +
			"LEFT JOIN ( " +
			"    SELECT p.id, p.license_application_id, p.payment_status, p.amount_paid, " +
			"           p.payment_method, p.date_created, p.fees_type_id, " +
			"           ROW_NUMBER() OVER (PARTITION BY p.license_application_id ORDER BY p.date_created DESC) as rn " +
			"    FROM core_application_payment p " +
			") latest_payment ON latest_payment.license_application_id = app.id AND latest_payment.rn = 1 " +
			"LEFT JOIN core_fees_type fees ON latest_payment.fees_type_id = fees.id " +
			"LEFT JOIN core_application_step step ON app.application_step_id = step.id " +
			"LEFT JOIN sys_user_account user_account ON app.user_account_id = user_account.id " +
			"WHERE LOWER(g.name) = LOWER(:roleName) " +
			"AND DATE(app.date_created) BETWEEN COALESCE(:dateFrom, '1900-01-01') AND COALESCE(:dateTo, '2100-12-31') " +
			"GROUP BY app.id, app.application_type, app.date_submitted, app.date_created, " +
			"         status.name, type.name, type.id, latest_payment.payment_status, fees.name, " +
			"         app.application_metadata, app.client_info, app.location_info, app.form_specific_data, " +
			"         step.id, step.name, step.sequence_number, " +
			"         user_account.id, user_account.first_name, user_account.last_name, user_account.username, user_account.email_address, " +
			"         latest_payment.amount_paid, latest_payment.id, latest_payment.payment_method, latest_payment.date_created, " +
			"         app.application_priority, app.emergency_reason, app.emergency_justification_file, app.emergency_submitted_date, " +
			"         app.license_fee " +
			"ORDER BY app.date_created DESC",
			countQuery = "SELECT COUNT(DISTINCT app.id) FROM core_license_application app " +
					"INNER JOIN core_license_application_activity act ON act.license_application_id = app.id " +
					"INNER JOIN sys_user_account u ON u.id = act.user_account_id " +
					"INNER JOIN sys_user_group g ON g.id = u.user_group_id " +
					"WHERE LOWER(g.name) = LOWER(:roleName) " +
					"AND DATE(app.date_created) BETWEEN COALESCE(:dateFrom, '1900-01-01') AND COALESCE(:dateTo, '2100-12-31')",
			nativeQuery = true)
	org.springframework.data.domain.Page<Object[]> findApplicationHistoryByRoleWithDateFilter(
			@Param("roleName") String roleName,
			@Param("dateFrom") String dateFrom,
			@Param("dateTo") String dateTo,
			Pageable pageable);

	/**
	 * OPTIMIZED: Returns ALL applications with date filtering (for DRS and admin users)
	 * Uses window function (ROW_NUMBER) instead of correlated subquery for better performance
	 * Note: Uses COALESCE to handle null date parameters
	 */
	@Query(value = "SELECT app.id, app.application_type, app.date_submitted, app.date_created, " +
			"status.name, type.name, type.id, latest_payment.payment_status, fees.name, " +
			"app.application_metadata, app.client_info, app.location_info, app.form_specific_data, " +
			"step.id, step.name, step.sequence_number, " +
			"user_account.id, user_account.first_name, user_account.last_name, user_account.username, user_account.email_address, " +
			"latest_payment.amount_paid, latest_payment.id, latest_payment.payment_method, latest_payment.date_created, " +
			"app.application_priority, app.emergency_reason, app.emergency_justification_file, app.emergency_submitted_date, " +
			"app.license_fee " +
			"FROM core_license_application app " +
			"LEFT JOIN core_application_status status ON app.application_status_id = status.id " +
			"LEFT JOIN core_license_type type ON app.license_type_id = type.id " +
			"LEFT JOIN ( " +
			"    SELECT p.id, p.license_application_id, p.payment_status, p.amount_paid, " +
			"           p.payment_method, p.date_created, p.fees_type_id, " +
			"           ROW_NUMBER() OVER (PARTITION BY p.license_application_id ORDER BY p.date_created DESC) as rn " +
			"    FROM core_application_payment p " +
			") latest_payment ON latest_payment.license_application_id = app.id AND latest_payment.rn = 1 " +
			"LEFT JOIN core_fees_type fees ON latest_payment.fees_type_id = fees.id " +
			"LEFT JOIN core_application_step step ON app.application_step_id = step.id " +
			"LEFT JOIN sys_user_account user_account ON app.user_account_id = user_account.id " +
			"WHERE DATE(app.date_created) BETWEEN COALESCE(:dateFrom, '1900-01-01') AND COALESCE(:dateTo, '2100-12-31') " +
			"ORDER BY app.date_created DESC",
			countQuery = "SELECT COUNT(app.id) FROM core_license_application app " +
					"WHERE DATE(app.date_created) BETWEEN COALESCE(:dateFrom, '1900-01-01') AND COALESCE(:dateTo, '2100-12-31')",
			nativeQuery = true)
	org.springframework.data.domain.Page<Object[]> findAllApplicationHistoryWithDateFilter(
			@Param("dateFrom") String dateFrom,
			@Param("dateTo") String dateTo,
			Pageable pageable);

}
