package mw.nwra.ewaterpermit.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreWaterSource;
import mw.nwra.ewaterpermit.model.CoreWaterSourceType;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreWaterSourceRepository extends JpaRepository<CoreWaterSource, String> {

	CoreWaterSource findByName(String name);

	List<CoreWaterSource> findByCoreWaterSourceType(CoreWaterSourceType wSourceType);

}
