package mw.nwra.ewaterpermit.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreWaterResourceArea;
import mw.nwra.ewaterpermit.model.CoreWaterResourceUnit;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreWaterResourceUnitRepository extends JpaRepository<CoreWaterResourceUnit, String> {

	List<CoreWaterResourceUnit> findByCoreWaterResourceArea(CoreWaterResourceArea area);

	List<CoreWaterResourceUnit> findByCoreWaterResourceAreaId(String areaId);

//	CoreWaterResourceUnit findByName(String name);

}
