package mw.nwra.ewaterpermit.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.CoreCustomerType;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreCustomerTypeRepository extends JpaRepository<CoreCustomerType, String> {

	CoreCustomerType findByName(String name);

}
