package mw.nwra.ewaterpermit.repository;

import java.util.List;

import mw.nwra.ewaterpermit.dto.PaymentSummaryDTO;
import mw.nwra.ewaterpermit.model.CoreLicense;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import mw.nwra.ewaterpermit.model.CoreApplicationPayment;

/**
 * Generated by Spring Data Generator on 20/02/2025
 */
@Repository
public interface CoreApplicationPaymentRepository extends JpaRepository<CoreApplicationPayment, String> {

	@Query("SELECT p FROM CoreApplicationPayment p WHERE "
			+ " p.coreLicenseApplication.destOwnerFullname LIKE %:search% OR "
			+ " p.coreLicenseApplication.sourceOwnerFullname LIKE %:search% OR "
			+ " p.coreLicenseApplication.destPlotNumber  LIKE %:search%")
	Page<CoreApplicationPayment> findAll(@Param("search") String search, Pageable pageable);

	/**
	 * Find all payments for a specific license application
	 */
	@Query("SELECT p FROM CoreApplicationPayment p WHERE p.coreLicenseApplication.id = :applicationId")
	List<CoreApplicationPayment> findByCoreLicenseApplicationId(@Param("applicationId") String applicationId);

	/**
	 * OPTIMIZED: Batch fetch payments for multiple applications in a single query
	 * Eagerly loads all related entities to prevent N+1 queries
	 */
	@Query("SELECT p FROM CoreApplicationPayment p " +
		   "LEFT JOIN FETCH p.coreFeesType " +
		   "LEFT JOIN FETCH p.coreFinancialYear " +
		   "WHERE p.coreLicenseApplication.id IN :applicationIds " +
		   "ORDER BY p.dateCreated DESC")
	List<CoreApplicationPayment> findByLicenseApplicationIdIn(@Param("applicationIds") List<String> applicationIds);

	/**
	 * Find application fee payments for a specific license application (optimized)
	 */
	@Query("SELECT p FROM CoreApplicationPayment p JOIN FETCH p.coreFeesType ft " +
		   "WHERE p.coreLicenseApplication.id = :applicationId " +
		   "AND p.paymentStatus = 'AWAITING_APPROVAL' " +
		   "AND ft.name = 'Application fee'")
	List<CoreApplicationPayment> findApplicationFeePayments(@Param("applicationId") String applicationId);

	/**
	 * Find license fee payments for a specific license application (optimized)
	 */
	@Query("SELECT p FROM CoreApplicationPayment p JOIN FETCH p.coreFeesType ft " +
		   "WHERE p.coreLicenseApplication.id = :applicationId " +
		   "AND p.paymentStatus = 'AWAITING_APPROVAL' " +
		   "AND ft.name = 'License fees'")
	List<CoreApplicationPayment> findLicenseFeePayments(@Param("applicationId") String applicationId);

    List<CoreApplicationPayment> findByCoreLicense(CoreLicense coreLicense);

	/**
	 * Find all PAID payments for a specific financial year
	 */
	@Query("SELECT p FROM CoreApplicationPayment p WHERE p.coreFinancialYear.id = :financialYearId AND p.paymentStatus = 'PAID'")
	List<CoreApplicationPayment> findByFinancialYearId(@Param("financialYearId") String financialYearId);

	/**
	 * Check if license fees are paid for a specific license using native query
	 */
	@Query(value = """
		SELECT COUNT(*) > 0 
		FROM core_application_payment p 
		JOIN core_license l ON l.license_application_id = p.license_application_id 
		JOIN core_fees_type ft ON p.fees_type_id = ft.id 
		WHERE l.id = :licenseId 
		AND ft.name = 'License fees' 
		AND p.payment_status = 'PAID'
	""", nativeQuery = true)
	boolean isLicenseFeePaidForLicense(@Param("licenseId") String licenseId);

	/**
	 * Optimized query to get payment summaries for multiple applications
	 */
	@Query("""
		SELECT new mw.nwra.ewaterpermit.dto.PaymentSummaryDTO(
			payment.id,
			payment.coreLicenseApplication.id,
			payment.paymentStatus,
			COALESCE(feesType.name, 'Unknown'),
			payment.amountPaid,
			payment.paymentMethod
		)
		FROM CoreApplicationPayment payment
		LEFT JOIN payment.coreFeesType feesType
		WHERE payment.coreLicenseApplication.id IN :applicationIds
		ORDER BY payment.dateCreated DESC
	""")
	List<PaymentSummaryDTO> findPaymentSummariesByApplicationIds(
		@Param("applicationIds") List<String> applicationIds
	);

	/**
	 * Calculate total revenue using database aggregation - much more efficient than loading all records
	 */
	@Query("""
		SELECT COALESCE(SUM(payment.amountPaid), 0)
		FROM CoreApplicationPayment payment 
		WHERE UPPER(payment.paymentStatus) IN ('VERIFIED', 'PAID', 'COMPLETED', 'APPROVED')
		AND payment.amountPaid > 0
	""")
	Double calculateTotalRevenue();

	/**
	 * Get payment statistics by status using database aggregation
	 */
	@Query("""
		SELECT payment.paymentStatus, COUNT(payment), SUM(COALESCE(payment.amountPaid, 0))
		FROM CoreApplicationPayment payment
		GROUP BY payment.paymentStatus
	""")
	List<Object[]> getPaymentStatsByStatus();

	/**
	 * Calculate monthly revenue for current month using database aggregation
	 */
	@Query("""
		SELECT COALESCE(SUM(payment.amountPaid), 0)
		FROM CoreApplicationPayment payment
		WHERE MONTH(payment.dateCreated) = MONTH(CURRENT_DATE)
		AND YEAR(payment.dateCreated) = YEAR(CURRENT_DATE)
		AND UPPER(payment.paymentStatus) IN ('VERIFIED', 'PAID', 'COMPLETED', 'APPROVED')
		AND payment.amountPaid > 0
	""")
	Double calculateMonthlyRevenue();

	/**
	 * Get payment method distribution using database aggregation
	 */
	@Query("""
		SELECT COALESCE(payment.paymentMethod, 'Unknown'),
		       COUNT(payment),
		       SUM(COALESCE(payment.amountPaid, 0))
		FROM CoreApplicationPayment payment
		GROUP BY payment.paymentMethod
	""")
	List<Object[]> getPaymentMethodDistribution();

	/**
	 * Get recent payments (limit 10) with minimal data
	 */
	@Query("""
		SELECT payment.id, payment.dateCreated, payment.amountPaid,
		       payment.paymentStatus, payment.paymentMethod
		FROM CoreApplicationPayment payment
		ORDER BY payment.dateCreated DESC
	""")
	List<Object[]> getRecentPayments(Pageable pageable);

	/**
	 * Approve payment by application ID and fee type using optimized update query
	 */
	@Modifying
	@Transactional
	@Query(value = """
		UPDATE core_application_payment cap 
		SET cap.payment_status = 'PAID', 
		    cap.verification_date = CURRENT_TIMESTAMP,
		    cap.date_updated = CURRENT_TIMESTAMP
		WHERE cap.license_application_id = :applicationId 
		AND cap.fees_type_id = (
		    SELECT ft.id FROM core_fees_type ft WHERE ft.name = :feeTypeName
		)
		AND cap.payment_status = 'AWAITING_APPROVAL'
	""", nativeQuery = true)
	int approvePaymentByApplicationAndFeeType(@Param("applicationId") String applicationId, 
	                                          @Param("feeTypeName") String feeTypeName);

	/**
	 * Get application step sequence number using lightweight query
	 */
	@Query("""
		SELECT step.sequenceNumber 
		FROM CoreLicenseApplication app 
		JOIN app.coreApplicationStep step 
		WHERE app.id = :applicationId
	""")
	Integer getApplicationStepSequence(@Param("applicationId") String applicationId);

	/**
	 * Update application step using optimized query
	 */
	@Modifying
	@Transactional
	@Query("""
		UPDATE CoreLicenseApplication app 
		SET app.coreApplicationStep.id = :nextStepId,
		    app.dateUpdated = CURRENT_TIMESTAMP
		WHERE app.id = :applicationId
	""")
	int updateApplicationStep(@Param("applicationId") String applicationId, 
	                         @Param("nextStepId") String nextStepId);

	/**
	 * Update payment receipt document status using optimized query
	 */
	@Modifying
	@Transactional
	@Query(value = """
		UPDATE core_application_document cad
		SET cad.status = 'PAID',
		    cad.date_updated = CURRENT_TIMESTAMP
		WHERE cad.license_application_id = :applicationId
		AND cad.document_category_id = (
		    SELECT cdc.id FROM core_document_category cdc WHERE cdc.name = 'Payment Receipt'
		)
	""", nativeQuery = true)
	int updatePaymentReceiptStatus(@Param("applicationId") String applicationId);

	/**
	 * Find all payments with application details using eager fetching
	 */
	@Query("SELECT DISTINCT p FROM CoreApplicationPayment p " +
			"LEFT JOIN FETCH p.coreFeesType " +
			"LEFT JOIN FETCH p.coreLicenseApplication app " +
			"LEFT JOIN FETCH app.sysUserAccount user " +
			"LEFT JOIN FETCH app.coreApplicationStatus " +
			"LEFT JOIN FETCH app.coreApplicationStep " +
			"LEFT JOIN FETCH app.coreLicenseType " +
			"WHERE CAST(p.amountPaid AS string) LIKE %:search% OR " +
			"app.id LIKE %:search% OR " +
			"user.firstName LIKE %:search% OR " +
			"user.lastName LIKE %:search% OR " +
			"user.emailAddress LIKE %:search%")
	Page<CoreApplicationPayment> findAllPaymentsWithDetails(@Param("search") String search, Pageable pageRequest);
}
