package mw.nwra.ewaterpermit.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.SysAuditEntry;

/**
 * Generated by Spring Data Generator on 06/02/2023
 */
@Repository
public interface SysAuditEntryRepository extends JpaRepository<SysAuditEntry, String> {

	@Query("SELECT e FROM SysAuditEntry e WHERE " + " e.action LIKE %:search% OR " + " e.keyValue LIKE %:search% OR "
			+ " e.newValue LIKE %:search% OR " + " e.tableName LIKE %:search% OR "
			+ " e.sysUserAccount.firstName LIKE %:search% OR " + " e.sysUserAccount.lastName LIKE %:search% OR "
			+ " e.fieldName  LIKE %:search%")
	Page<SysAuditEntry> findAll(@Param("search") String search, Pageable pageable);

}
