package mw.nwra.ewaterpermit.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.SysEmailTemplate;

/**
 * Generated by Spring Data Generator on 06/02/2023
 */
@Repository
public interface SysEmailTemplateRepository extends JpaRepository<SysEmailTemplate, String> {

	List<SysEmailTemplate> findByNameIgnoreCaseAndStatus(String name, Short status);

}
