package mw.nwra.ewaterpermit.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.SysObject;

/**
 * Generated by Spring Data Generator on 06/02/2023
 */
@Repository
public interface SysObjectRepository extends JpaRepository<SysObject, String> {

	@Query("SELECT s FROM SysObject s WHERE s.name LIKE %:search% OR s.description LIKE %:search%")
	Page<SysObject> findAll(@Param("search") String search, Pageable pageable);

	SysObject findByName(String name);

}
