package mw.nwra.ewaterpermit.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.SysPermission;

/**
 * Generated by Spring Data Generator on 06/02/2023
 */
@Repository
public interface SysPermissionRepository extends JpaRepository<SysPermission, String> {

	SysPermission findByName(String name);

}
