package mw.nwra.ewaterpermit.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.SysUserGroup;

/**
 * Generated by Spring Data Generator on 06/02/2023
 */
@Repository
public interface SysUserGroupRepository extends JpaRepository<SysUserGroup, String> {

	SysUserGroup findByName(String name);

	SysUserGroup findByNameIgnoreCase(String name);

}
