package mw.nwra.ewaterpermit.repository;

import java.sql.Timestamp;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.SysUserAccountActivation;

/**
 * Generated by Spring Data Generator on 06/02/2023
 */
@Repository
public interface SysUserAccountActivationRepository extends JpaRepository<SysUserAccountActivation, String> {

	@Query("SELECT a FROM SysUserAccountActivation a WHERE a.token=:token AND a.dateActivated IS NULL AND a.dateExpired >:dateTimeNow")
	SysUserAccountActivation findUnconfirmedRegistration(@Param("token") String token,
			@Param("dateTimeNow") Timestamp dateTimeNow);

	@Query("SELECT a FROM SysUserAccountActivation a WHERE a.token=:token AND a.dateActivated IS NULL AND a.dateExpired >:dateTimeNow AND a.emailAddress =:email")
	SysUserAccountActivation findUnconfirmedRegistration(@Param("token") String token,
			@Param("dateTimeNow") Timestamp dateTimeNow, @Param("email") String email);

	@Query("SELECT a FROM SysUserAccountActivation a WHERE a.token=:token")
	SysUserAccountActivation findByToken(@Param("token") String token);

}
