package mw.nwra.ewaterpermit.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import mw.nwra.ewaterpermit.model.SysUserGroup;
import mw.nwra.ewaterpermit.model.SysUserGroupPermission;

/**
 * Generated by Spring Data Generator on 06/02/2023
 */
@Repository
public interface SysUserGroupPermissionRepository extends JpaRepository<SysUserGroupPermission, String> {

	List<SysUserGroupPermission> findBySysUserGroup(SysUserGroup userGroup);

}
